"use strict";$(document).ready(function(){$('#testmonials-carousel').owlCarousel({loop:!1,responsiveClass:!0,nav:!0,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1,nav:!1,dots:!0,margin:10,},600:{items:1,nav:!1,dots:!0,margin:15,},1000:{items:1,dots:!1,margin:40,}}})
$('#services-carousel').owlCarousel({loop:!1,responsiveClass:!0,dots:!1,nav:!0,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1,margin:15,},600:{items:2,margin:30,},1000:{items:3,margin:0,}}})
$('#blog-grid').owlCarousel({loop:!1,dots:!0,nav:!1,autoplay:!0,autoplayTimeout:2500,responsiveClass:!0,autoplayHoverPause:!1,responsive:{0:{items:1,margin:0,},600:{items:2,margin:0,},1000:{items:3,margin:0,}}})
$('#clients').owlCarousel({loop:!0,nav:!1,dots:!1,autoplay:!0,autoplayTimeout:3000,responsiveClass:!0,autoplayHoverPause:!1,responsive:{0:{items:2,margin:50,},600:{items:3,margin:30,},1000:{items:6,margin:40,}}})
$('#project-single').owlCarousel({loop:!1,nav:!1,responsiveClass:!0,dots:!1,responsive:{0:{items:1,margin:15,},600:{items:2,margin:15,},1000:{items:3,margin:15}}})
$('.countup').counterUp({delay:25,time:2000});if($(".swiper-main-slider").length!==0){var swiper=new Swiper('.swiper-container',{navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},pagination:{el:'.swiper-pagination',dynamicBullets:!0,},pagination:'.swiper-pagination',paginationClickable:!0,nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev',spaceBetween:0,loop:!0,simulateTouch:!0,autoplay:5000,speed:1000,onSlideChangeEnd:function(swiper){$('.swiper-slide').each(function(){if($(this).index()===swiper.activeIndex){$(this).find('.slider-content').fadeIn(300)}else{$(this).find('.slider-content').fadeOut(300)}})}})}
if($(".swiper-main-slider-fade").length!==0){var swiper=new Swiper('.swiper-container',{effect:'fade',navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},pagination:{el:'.swiper-pagination',dynamicBullets:!0,},pagination:'.swiper-pagination',paginationClickable:!0,nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev',spaceBetween:0,loop:!0,simulateTouch:!0,autoplay:5000,speed:1000,onSlideChangeEnd:function(swiper){$('.swiper-slide').each(function(){if($(this).index()===swiper.activeIndex){$(this).find('.slider-content').fadeIn(300)}else{$(this).find('.slider-content').fadeOut(300)}})}})}
if($("#swiper-parallax").length!==0){var swiper=new Swiper('.swiper-container',{parallax:!0,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},pagination:{el:'.swiper-pagination',dynamicBullets:!0,},pagination:'.swiper-pagination',paginationClickable:!0,nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev',spaceBetween:0,loop:!1,simulateTouch:!0,autoplay:!1,speed:1000,})}
if($("#rev_slider_24_1").length!==0){var tpj=jQuery;var revapi24;tpj(document).ready(function(){if(tpj("#rev_slider_24_1").revolution==undefined){revslider_showDoubleJqueryError("#rev_slider_24_1")}else{revapi24=tpj("#rev_slider_24_1").show().revolution({sliderType:"standard",jsFileLocation:"revolution/js/",sliderLayout:"fullscreen",dottedOverlay:"none",delay:9000,navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"off",bullets:{enable:!0,hide_onmobile:!1,style:"bullet-bar",hide_onleave:!1,direction:"horizontal",h_align:"center",v_align:"bottom",h_offset:0,v_offset:50,space:5,tmp:''}},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,1024,778,480],gridwidth:[1240,1024,778,480],gridheight:[868,768,960,720],lazyType:"none",shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",fullScreenAutoWidth:"off",fullScreenAlignForce:"off",fullScreenOffsetContainer:"",fullScreenOffset:"60px",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1,}})}
if(revapi24)revapi24.revSliderSlicey()})}
if($(window).width()>1200){$('ul.nav li.dropdown').hover(function(){$(this).find('.dropdown-menu').stop(!0,!0).delay(100).fadeIn(300)},function(){$(this).find('.dropdown-menu').stop(!0,!0).delay(100).fadeOut(300)})}
if($(".video-section").length!==0){$('.player').mb_YTPlayer()}
if($(".main-video-section").length!==0){$('#main-video-play').mb_YTPlayer()}
$('.modal').on('hidden.bs.modal',function(){var $this=$(this).find('iframe'),tempSrc=$this.attr('src');$this.attr('src',"");$this.attr('src',tempSrc)});$('#preloader').fadeOut('normall',function(){$(this).remove()});$(window).scroll(function(){if($(this).scrollTop()>500){$(".scroll-to-top").fadeIn(400)}else{$(".scroll-to-top").fadeOut(400)}});$(".scroll-to-top").on('click',function(event){event.preventDefault();$("html, body").animate({scrollTop:0},600)});var $grid=$('.isotope-grid').isotope({itemSelector:'.isotope-item',layoutMode:'fitRows',getSortData:{name:'.name',symbol:'.symbol',number:'.number parseInt',category:'[data-category]',weight:function(itemElem){var weight=$(itemElem).find('.weight').text();return parseFloat(weight.replace(/[\(\)]/g,''))}}});var filterFns={ium:function(){var name=$(this).find('.name').text();return name.match(/ium$/)}};$('#filters').on('click','button',function(){var filterValue=$(this).attr('data-filter');filterValue=filterFns[filterValue]||filterValue;$grid.isotope({filter:filterValue})});$('.parent-isotope').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','button',function(){$buttonGroup.find('.is-checked').removeClass('is-checked');$(this).addClass('is-checked')})});new WOW().init()});function openNav(){document.getElementById("search_nav").style.width="100%"}
function closeNav(){document.getElementById("search_nav").style.width="0%"}
jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.quantity input');jQuery('.quantity').each(function(){var spinner=jQuery(this),input=spinner.find('input[type="number"]'),btnUp=spinner.find('.quantity-up'),btnDown=spinner.find('.quantity-down'),min=input.attr('min'),max=input.attr('max');btnUp.on("click",function(){var oldValue=parseFloat(input.val());if(oldValue>=max){var newVal=oldValue}else{var newVal=oldValue+1}
spinner.find("input").val(newVal);spinner.find("input").trigger("change")});btnDown.on("click",function(){var oldValue=parseFloat(input.val());if(oldValue<=min){var newVal=oldValue}else{var newVal=oldValue-1}
spinner.find("input").val(newVal);spinner.find("input").trigger("change")})});$('.close-box').on("click",function(){$(this).parentsUntil('.row').slideToggle();return!1});$('.tabs_animate').tabslet({mouseevent:'click',attribute:'href',animation:!0});if($(".chartjs-render-monitor").length!==0){var randomScalingFactor=function(){return Math.round(Math.random()*100)};var config={type:'pie',data:{datasets:[{data:[randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),],backgroundColor:[window.chartColors.red,window.chartColors.orange,window.chartColors.green,window.chartColors.blue,],label:'Dataset 1'}],labels:["Red","Orange","Green","Blue"]},options:{responsive:!0}};window.onload=function(){var ctx=document.getElementById("chart-area").getContext("2d");window.myPie=new Chart(ctx,config)};document.getElementById('randomizeData').addEventListener('click',function(){config.data.datasets.forEach(function(dataset){dataset.data=dataset.data.map(function(){return randomScalingFactor()})});window.myPie.update()});var colorNames=Object.keys(window.chartColors);document.getElementById('addDataset').addEventListener('click',function(){var newDataset={backgroundColor:[],data:[],label:'New dataset '+config.data.datasets.length,};for(var index=0;index<config.data.labels.length;++index){newDataset.data.push(randomScalingFactor());var colorName=colorNames[index%colorNames.length];var newColor=window.chartColors[colorName];newDataset.backgroundColor.push(newColor)}
config.data.datasets.push(newDataset);window.myPie.update()});document.getElementById('removeDataset').addEventListener('click',function(){config.data.datasets.splice(0,1);window.myPie.update()})}